### PR TITLE
Write RST Preview to an HTML file instead of running a server

### PR DESCRIPTION
**Pull request by girasquid**
I was having problems with the plugin crashing when I tried to re-preview a few too many times - writing to a tempfile and loading that in the browser seems to have less problems.

### CODE REVIEW

**Comment by d0ugal** [comment]
Ah, interesting. This seems to be a much better way to do this - not sure why I didn't think of it before. I've only quickly scanned your changes, so you may already handle this. It seems like we should remember the tempfile location for each rst file (stored based on the path?) and then update that each time rather than creating a new one. This would have the added benefit of old tabs supporting refresh - then we could have two shortcuts - one to render and one to render and open in a new tab. Also, should we do a cleanup when sublime is closed? (I'm not sure there is even a hook for shutdown, but imagine there would be.)

**Comment by girasquid** [comment]
Looking back through the history, it looks like this is how RstPreview worked originally - but then in cc2743cd1d5c1b91caedec50f4238cbde8fc84df, it was switched to the server-serving-an-HTML-page style. Do you remember why you made the change?

Because the tempfile is made by just adding 'rst_preview.html' to the temp directory, the path doesn't seem to change very frequently - I only tested in one Sublime session though, so I will do some more tests and try to figure out when it _does_ change.

Because it's in a temp directory, I think the OS might take care of doing the cleanup for us - but if there's a way to hook into shutdown, that probably makes sense too. I will look into it. _Edit_: after looking into it on OS X, the OS will clean up the temp file when you shut down/restart, but not when you log out. Still looking into hooking sublime closing.

**Comment by d0ugal** [comment]
I _think_ I switched to the current approach to avoid having lots of tempfiles. However, I don't fully remember.

I think all OSes will only remove temp files on restart. Either way they should be small enough that I don't think it really matters if we can't tidy up. I had mistaken your call to `gettemptdir` as a call to `mkdtemp` which creates a new directory each time. So this doesn't seem like it will be an issue as it will not change very often at all.

**Comment by d0ugal** [comment]
I think this change is probably good to go. There is one thing I can't quite decide about - should we take into account multiple files? For example, if I'm switching between three RST files in sublime and the browser. I then refresh the browser it will switch to the latest rendered even if I wanted a tab for each. That could be a little annoying.

We could do something like take a hash of the full filepath and use that for the temp filename.

I'm not sure its worth the extra effort however.

**Comment by girasquid** [comment]
It wasn't that hard, so I did it - you might wind up with a few more temp files this way, but you'll be able to refresh them without losing the one you were looking at.

**Comment by d0ugal** [comment]
Awesome! Thanks! :cake:

**Pull request merged**
